CustomTransaction/CustomTransaction/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('CustomTransaction/',include('CustomTransactionReport.urls')),
]

CustomTransaction/CustomTransactionReport/urls.py
from django.urls import path
from . import views

app_name='Transaction'

urlpatterns = [
    path('test', views.filter, name='test'),
    path('Home', views.Home_page, name = 'Home'),
    path('Product_volume_report', views.product_volume_report, name = 'product_volume'),
    path('Product_value_report', views.product_value_report, name = 'product_value'),
    path('Customer_volume_report', views.customer_volume_report, name = 'customer_volume'),
    path('customer_value_report', views.customer_value_report, name = 'customer_value'),
    path('filter/<str:name>', views.filter, name = 'filter'),
    path('login', views.login, name = 'login'),
    path('registration', views.registration, name = 'registration'),
    path('logout', views.logout, name = 'logout')
]

CustomTransaction/CustomTransactionReport/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

# class Student(models.Model):
#     name = models.CharField(max_length = 256)

#     def __str__(self):
#         return f'crazy stuff {self.name}'

# class Marks(models.Model):
#     subject_name = models.CharField(max_length = 128)
#     score = models.IntegerField()
#     student = models.ForeignKey(Student, on_delete=models.CASCADE)

class Transcations(models.Model):

    customer_name = models.CharField(max_length = 256)
    merchant_name = models.ForeignKey(User, on_delete = models.CASCADE)
    pin_Code = models.IntegerField()
    date_field = models.DateField()
    total_Transaction = models.IntegerField()

    def __str__(self):
        return self.customer_name

# class customer(models.Model):
#     full_name = models.CharField(max_length = 256)
#     user = models.ForeignKey(User, on_delete = models.CASCADE)

class Product(models.Model):
    product_name = models.CharField(max_length = 256)
    cost = models.IntegerField()

    def __str__(self):
        return self.product_name

class Cart(models.Model):
    customer = models.ForeignKey(Transcations, on_delete = models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def subtotal(self):
        return self.product.cost * self.quantity
        # return 'hari'

# class Customer_volume_report(models.Model):
#     customer = models.ForeignKey(Transcations, on_delete = models.CASCADE)
#     product = models.ForeignKey(Product, on_delete=models.CASCADE)
#     cart = models.ForeignKey(Cart, on_delete=models.CASCADE)

    # def customer_name(self):
    #     cust_dict_ = {}
    #     name = self.customer.customer_name
        




    

CustomTransaction/CustomTransactionReport/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Transcations, Product, Cart
from django.contrib.auth import authenticate
import json

filter_data = []
additional_filter = []

def filter(request, name):
    # global Name, pincode , amount_lower, amount_upper\
    global additional_filter
    # filter_data = date_time_filter
    if request.method == 'POST':
        # name_filter = Transcations.objects
        if request.POST.get('customer_name') != "":
            Name = request.POST.get('customer_name')
            additional_filter = additional_filter.filter(customer_name = Name)
        if request.POST.get('pin_code') != "":
            pincode = request.POST.get('pin_code')
            additional_filter = additional_filter.filter(pin_Code = pincode)
        if request.POST.get('amount_upper') != "":
            amount_upper = request.POST.get('amount_upper')
            additional_filter = additional_filter.filter(total_Transaction__lt = amount_upper)
        if request.POST.get('amount_lower') != "":
            amount_lower = request.POST.get('amount_lower')
            additional_filter = additional_filter.filter(total_Transaction__gt = amount_lower)
        # filter_data = filter_data.all()
        
        # return HttpResponse(f"{filter_data}")
    # return render(request, 'CustomerTransactionReport/index.html')
        return redirect(f'Transaction:{name}')

def Home_page(request):
    # name = 'harish'
    global filter_data, additional_filter
    # request.session['date_from'] = None
    # request.session['date_to'] = None
    if request.session.get('Access'):
        filter_data = Transcations.objects
        if request.method == 'POST':
            report_type = request.POST.get('report_type')
            if request.POST.get('date_from') != "":
                # Name = request.POST.get('customer_name')
                date_from = request.POST.get('date_from')
                request.session['date_from'] = date_from
                filter_data = filter_data.filter(date_field__gt = date_from)
                # print(filter_data)
                # return HttpResponse(f"{filter_data}")
            if request.POST.get('date_to') != "":
                date_to = request.POST.get('date_to')
                request.session['date_to'] = date_to
                filter_data = filter_data.filter(date_field__lt = date_to)
                # print(filter_data)
                # return HttpResponse(f"{filter_data}")
            # print(filter_data.all())
            filter_data = filter_data.all()
            additional_filter = filter_data
            print(filter_data)
            # return HttpResponse(f"{filter_data}")
            # filter_data.all()
            # report_type = request.POST.get('report_type')
            # print(filter_data)
            # return(f"{filter_data}")
            return redirect(f'Transaction:{report_type}')
        
        return render(request, 'CustomerTransactionReport/index.html')
    return HttpResponse("""please login <a href ="http://127.0.0.1:8000/CustomTransaction/login">here</a> to access the page""")
        


def product_volume_report(request):
    name = 'product_volume'
    #filter
    global additional_filter, filter_data
    Product_volume_dict_ = {}
    list_ = []
    for filter in additional_filter:
        list_ += Cart.objects.filter(customer = filter)
    products = list_
    # products = Cart.objects.all()
    # --------------------------------------
    # pincode_filter = Transcations.objects.filter(pin_Code = 508211)
    # list_ = []
    # for filter in pincode_filter:
    #     list_ += Cart.objects.filter(customer = filter)
    # products = list_
    # -----------------------------------
    # name_filter = Transcations.objects.get(customer_name = "Harish")
    # products = Cart.objects.filter(customer = name_filter)
    for product_ in products:
        if product_.product.product_name in Product_volume_dict_:
            Product_volume_dict_[product_.product.product_name] += product_.quantity
        else:
            Product_volume_dict_[product_.product.product_name] = product_.quantity

    # Product_volume_dict_[product_name] = quantity
    additional_filter = filter_data
    json_data = json.dumps(Product_volume_dict_)
    # json_data = ""
    context = {'product_volume': Product_volume_dict_, 'name':name, 'date_from':request.session.get('date_from'), 'date_to':request.session.get('date_to'), 'json_data':json_data}
    return render(request,'CustomerTransactionReport/product_volume_report.html',context)

def product_value_report(request):
    name = 'product_value'
    #filter
    global additional_filter, filter_data
    Product_value_dict_ = {}
    list_ = []
    for filter in additional_filter:
        list_ += Cart.objects.filter(customer = filter)
    products = list_
    # Product_value_dict_ = {}
    # products = Cart.objects.all()
    for product_ in products:
        
        if product_.product.product_name in Product_value_dict_:
            Product_value_dict_[product_.product.product_name] += int(product_.subtotal())
        else:
            Product_value_dict_[product_.product.product_name] = int(product_.subtotal())
    # context = {'product_volume': product_volume_dict_}
    # return HttpResponse(f"<p>{Product_value_dict_}</p>")
    additional_filter = filter_data
    json_data = json.dumps(Product_value_dict_)
    context = {'product_value': Product_value_dict_, 'name':name, 'json_data':json_data}
    return render(request,'CustomerTransactionReport/product_value_report.html',context)

def customer_value_report(request):
    name = 'customer_value'
    #filter
    global additional_filter, filter_data
    # Product_value_dict_ = {}
    list_ = []
    for filter in additional_filter:
        list_ += Cart.objects.filter(customer = filter)
    products = list_
    customer_value_dict_ = {}
    # customers = Cart.objects.all()
    for customer_ in products:
        customer_value_dict_[customer_.customer.customer_name] = customer_.customer.total_Transaction

    # customer_volume_dict_[customer_name] = quantity
    # context = {'customer_volume': customer_volume_dict_}
    additional_filter = filter_data
    json_data = json.dumps(customer_value_dict_)
    context = {'customer_value': customer_value_dict_, 'name':name, 'json_data':json_data}
    return render(request,'CustomerTransactionReport/customer_value_report.html',context)
    # return HttpResponse(f"<p>{customer_value_dict_}</p>")

def customer_volume_report(request):
    name = 'customer_volume'
    #filter
    global additional_filter, filter_data
    # Product_value_dict_ = {}
    list_ = []
    for filter in additional_filter:
        list_ += Cart.objects.filter(customer = filter)
    products = list_
     # customer_value_dict_ = {}
    customer_volume_dict_ = {}
    # customers = Cart.objects.all()

    for customer_ in products:
        if customer_.customer.customer_name in customer_volume_dict_:
            customer_volume_dict_[customer_.customer.customer_name] += customer_.quantity
        else:
            customer_volume_dict_[customer_.customer.customer_name] = customer_.quantity

    # Product_volume_dict_[product_name] = quantity
    # context = {'product_volume': product_volume_dict_}
    # return HttpResponse(f"<p>{customer_volume_dict_}</p>")
    # customer_value_dict_[customer_name] = total_transaction
    # context = {'customer_volume': customer_value_dict_}
    # pass
    additional_filter = filter_data
    json_data = json.dumps(customer_volume_dict_)
    context = {'customer_volume': customer_volume_dict_,'name':name, 'json_data':json_data}
    return render(request,'CustomerTransactionReport/customer_volume_report.html',context)

def complete_report(request):
    name = 'complete_report'
    global additional_filter, filter_data
    Comlete_report_dict_ = {}
    list_ = []
    for filter in additional_filter:
        list_ += Cart.objects.filter(customer = filter)
    products = list_






def login(request):
    error_message = ''
    if request.method == 'POST':
        username_ = request.POST.get('username')
        password_ = request.POST.get('password')
        user = authenticate(username=username_, password=password_)
        if user is not None:
            request.session['logged_in_customer'] = user.username
            request.session['date_from'] = ""
            request.session['date_to'] = "Today"
            request.session['Access'] = True

            # owner = Owner.objects.get(user=user)
            context = {'error_message': error_message}
            return render(request, 'CustomerTransactionReport/index.html', context)
        else:
            error_message = 'Incorrect Password'
    context = {'error_message': error_message}
    return render(request, 'CustomerTransactionReport/login_page.html', context)

def logout(request):
    # del request.session['logged_in_student']
    del request.session['Access']
    return redirect('Transaction:login')

def registration(request):
    return render(request, 'CustomerTransactionReport/registration_page.html')

CustomTransaction/CustomTransactionReport/templates/CustomerTransactionReport/customer_value_report.html
<!DOCTYPE html>
<html>
<head>
	<title>Customer Value Report</title>
	<style>
		table {
			border-collapse: collapse;
			width: 100%;
			margin-top: 20px;
		}
		th, td {
			text-align: left;
			padding: 8px;
			border: 1px solid black;
		}
		th {
			background-color: #4CAF50;
			color: white;
		}
		main {
    max-width: 800px;
    margin: 0 auto;
    padding: 2em;
}

section {
    margin-bottom: 2em;
}

h2 {
    margin-top: 0;
}

form {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
    align-items: center;
}

fieldset {
    margin: 1em 0;
    border: none;
}

legend {
    font-size: 1.2em;
    font-weight: bold;
    margin-bottom: 0.5em;
}

label {
    display: block;
    margin-bottom: 0.5em;
}

input[type="number"],
input[type="date"],
input[type="text"],
select {
    padding: 0.5em;
    border-radius: 4px;
    border: 1px solid #ccc;
    font-size: 1em;
    margin-bottom: 0.5em;
}

button[type="submit"] {
    background-color: #4CAF50;
    color: #fff;
    border: none;
    padding: 0.5em 1em;
    border-radius: 4px;
    font-size: 1em;
    cursor: pointer;
}

button[type="submit"]:hover {
    background-color: #3e8e41;
}

#report_results {
    margin-top: 2em;
    padding: 1em;
    background-color: #f5f5f5;
}
	</style>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>
	<h1 style="text-align: center; color: green">Customer Value Report</h1>
	<p style=" text-align: center;">Report generated from 01/01/2023 to 01/31/2023</p>
	<section>
		<h2>Filter Settings</h2>
		<form method="POST" action="{% url 'Transaction:filter' name %}">
			{% csrf_token %}
			<fieldset>
				<legend>Total Amount</legend>
				<label for="amount_lower">Lower Limit:</label>
				<input type="number" id="amount_lower" name="amount_lower" min="0" step="1">
				<label for="amount_upper">Upper Limit:</label>
				<input type="number" id="amount_upper" name="amount_upper" min="0" step="1">
			</fieldset>
			<fieldset>
				<legend>PIN Code</legend>
				<label for="pin_code">PIN Code:</label>
				<input type="number" id="pin_code" name="pin_code" maxlength="6">
			</fieldset>
			<fieldset>
				<legend>Customer</legend>
				<label for="customer_name">Customer Name:</label>
				<input type="text" id="customer_name" name="customer_name">
			</fieldset>
			<button type="submit">Apply Filters</button>
		</form>
	</section>
	<section>
		<!-- <p>{{ customer_value }}</p> -->
        <div>
			<h2>Customer Value Pie Chart</h2>
			<!-- <img src="customer_volume_pie_chart.png" alt="Customer Volume Pie Chart"> -->
			<canvas id="myChart" width="1300" height="600"></canvas>
	
		<script>
			var jsonStr = '{{ json_data|escapejs|safe }}';
			var data = JSON.parse(jsonStr);
		
			// Convert dictionary data to arrays for chart.js
			var labels = Object.keys(data);
			var values = Object.values(data);
		
			// Create a pie chart
			var ctx = document.getElementById('myChart').getContext('2d');
			var myChart = new Chart(ctx, {
				type: 'pie',
				data: {
					labels: labels,
					datasets: [{
						data: values,
						borderWidth: 1
					}]
				},
				options: {
					responsive: false,
					maintainAspectRatio: false
				}
			});
		</script>
		</div>

		<p>Descriptive Statistics:</p>
	<table>
		<tr>
			<th>Customer Name</th>
			<th>Total Cost</th>
		</tr>
		{% for key, value in customer_value.items %}
		<tr>
			<td>{{ key }}</td>
			<td>{{ value }}</td>
			
		</tr>
		{% endfor %}
	</table>
    <p>click here to go <a href=" {% url 'Transaction:Home' %}">Home </a>page</p>
	</section>
</body>
</html>

CustomTransaction/CustomTransactionReport/templates/CustomerTransactionReport/customer_volume_report.html
<!DOCTYPE html>
<html>
<head>
	<title>Customer Volume Report</title>
	<style>
		table {
			border-collapse: collapse;
			width: 100%;
			margin-top: 20px;
		}
		th, td {
			text-align: left;
			padding: 8px;
			border: 1px solid black;
		}
		th {
			background-color: #4CAF50;
			color: white;
		}
		main {
    max-width: 800px;
    margin: 0 auto;
    padding: 2em;
}

section {
    margin-bottom: 2em;
}

h2 {
    margin-top: 0;
}

form {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
    align-items: center;
}

fieldset {
    margin: 1em 0;
    border: none;
}

legend {
    font-size: 1.2em;
    font-weight: bold;
    margin-bottom: 0.5em;
}

label {
    display: block;
    margin-bottom: 0.5em;
}

input[type="number"],
input[type="date"],
input[type="text"],
select {
    padding: 0.5em;
    border-radius: 4px;
    border: 1px solid #ccc;
    font-size: 1em;
    margin-bottom: 0.5em;
}

button[type="submit"] {
    background-color: #4CAF50;
    color: #fff;
    border: none;
    padding: 0.5em 1em;
    border-radius: 4px;
    font-size: 1em;
    cursor: pointer;
}

button[type="submit"]:hover {
    background-color: #3e8e41;
}

#report_results {
    margin-top: 2em;
    padding: 1em;
    background-color: #f5f5f5;
}
	</style>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>
	<h1 style="text-align: center; color:green;">Customer Volume Report</h1>
	<p style="text-align: center;">Report generated from 01/01/2023 to 01/31/2023</p>
	<section>
		<h2>Filter Settings</h2>
		<form method="POST" action="{% url 'Transaction:filter' name %}">
			{% csrf_token %}
			<fieldset>
				<legend>Total Amount</legend>
				<label for="amount_lower">Lower Limit:</label>
				<input type="number" id="amount_lower" name="amount_lower" min="0" step="1">
				<label for="amount_upper">Upper Limit:</label>
				<input type="number" id="amount_upper" name="amount_upper" min="0" step="1">
			</fieldset>
			<fieldset>
				<legend>PIN Code</legend>
				<label for="pin_code">PIN Code:</label>
				<input type="number" id="pin_code" name="pin_code" maxlength="6">
			</fieldset>
			<fieldset>
				<legend>Customer</legend>
				<label for="customer_name">Customer Name:</label>
				<input type="text" id="customer_name" name="customer_name">
			</fieldset>
			<button type="submit">Apply Filters</button>
		</form>
	</section>
	<section>
		<!-- <p>{{ customer_volume }}</p> -->
        <div>
			<h2>Customer Volume Pie Chart</h2>
			<!-- <img src="customer_volume_pie_chart.png" alt="Customer Volume Pie Chart"> -->
			<canvas id="myChart" width="1300" height="600"></canvas>
	
		<script>
			var jsonStr = '{{ json_data|escapejs|safe }}';
			var data = JSON.parse(jsonStr);
		
			// Convert dictionary data to arrays for chart.js
			var labels = Object.keys(data);
			var values = Object.values(data);
		
			// Create a pie chart
			var ctx = document.getElementById('myChart').getContext('2d');
			var myChart = new Chart(ctx, {
				type: 'pie',
				data: {
					labels: labels,
					datasets: [{
						data: values,
						borderWidth: 1
					}]
				},
				options: {
					responsive: false,
					maintainAspectRatio: false
				}
			});
		</script>
		</div>

		<p>Descriptive Statistics:</p>
	<table>
		<tr>
			<th>Customer Name</th>
			<th>Total Quantity</th>
		</tr>
		{% for key, value in customer_volume.items %}
		<tr>
			<td>{{ key }}</td>
			<td>{{ value }}</td>
			
		</tr>
		{% endfor %}
	</table>
    <p>click here to go <a href=" {% url 'Transaction:Home' %}">Home </a>page</p>
	</section>
</body>
</html>

CustomTransaction/CustomTransactionReport/templates/CustomerTransactionReport/index.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>Custom Transaction Reports</title>
	<!-- <link rel="stylesheet" href="style.css"> -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700&display=swap" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="style.css">
    <!-- <link rel="stylesheet" href="style.css"> -->
	<style>
		/* Global styles */
body {
    margin: 0;
    padding: 0;
    font-family: Arial, sans-serif;
    font-size: 16px;
    line-height: 1.5;
    color: #333;
}

/* Header styles */
header {
    background-color: #f5f5f5;
    padding: 1em;
    text-align: center;
}

header h1 {
    margin: 0;
}

/* Main section styles */
main {
    max-width: 800px;
    margin: 0 auto;
    padding: 2em;
}

section {
    margin-bottom: 2em;
}

h2 {
    margin-top: 0;
}

form {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
    align-items: center;
}

fieldset {
    margin: 1em 0;
    border: none;
}

legend {
    font-size: 1.2em;
    font-weight: bold;
    margin-bottom: 0.5em;
}

label {
    display: block;
    margin-bottom: 0.5em;
}

input[type="number"],
input[type="date"],
input[type="text"],
select {
    padding: 0.5em;
    border-radius: 4px;
    border: 1px solid #ccc;
    font-size: 1em;
    margin-bottom: 0.5em;
}

button[type="submit"] {
    background-color: #4CAF50;
    color: #fff;
    border: none;
    padding: 0.5em 1em;
    border-radius: 4px;
    font-size: 1em;
    cursor: pointer;
}

button[type="submit"]:hover {
    background-color: #3e8e41;
}

#report_results {
    margin-top: 2em;
    padding: 1em;
    background-color: #f5f5f5;
}


	</style>

</head>
<body>
	
	<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
		<a class="navbar-brand" href="#">Custom Transaction Report Login Page {{ name }}</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		  <span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarNav">
		  <ul class="navbar-nav ml-auto">
			<li class="nav-item active">
			  <a class="nav-link" href="#">{{ name }}</a>
			</li>
			<li class="nav-item">
			  <a class="nav-link" href="{% url 'Transaction:logout' %}">logout</a>
			</li>
		  </ul>
		</div>
	  </nav>
	<header>
		<h1>Custom Transaction Reports</h1>
	</header>
	<main>
		<section>
			<h2>Reports</h2>
			<form method="POST" action="{% url 'Transaction:Home' %}">
				{% csrf_token %}
				<fieldset>
					<legend>Date Range</legend>
					<label for="date_from">From:</label>
					<input type="date" id="date_from" name="date_from">
					<label for="date_to">To:</label>
					<input type="date" id="date_to" name="date_to">
				</fieldset>
				<fieldset>
					<legend>Report Type</legend>
					<label for="report_type">Select a report type:</label>
					<select id="report_type" name="report_type">
						<option value="product_volume">Product Volume Report</option>
						<option value="product_value">Product Value Report</option>
						<!-- <option value="complete">Complete Report</option> -->
						<option value="customer_volume">Customer Volume Report</option>
						<option value="customer_value">Customer Value Report</option>
					</select>
				</fieldset>
				<button type="submit">Generate Report</button>
			</form>
			<div id="report_results">
				<!-- Report results will be displayed here -->
			</div>
		</section>
	</main>
</body>
</html>

CustomTransaction/CustomTransactionReport/templates/CustomerTransactionReport/product_value_report.html
<!DOCTYPE html>
<html>
<head>
	<title>Product Volume Report</title>
    <!-- Add the following to the <head> section of your HTML template -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

	<style>
		table {
			border-collapse: collapse;
			width: 100%;
			margin-top: 20px;
		}
		th, td {
			text-align: left;
			padding: 8px;
			border: 1px solid black;
		}
		th {
			background-color: #4CAF50;
			color: white;
		}
		main {
    max-width: 800px;
    margin: 0 auto;
    padding: 2em;
}

section {
    margin-bottom: 2em;
}

h2 {
    margin-top: 0;
}

form {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
    align-items: center;
}

fieldset {
    margin: 1em 0;
    border: none;
}

legend {
    font-size: 1.2em;
    font-weight: bold;
    margin-bottom: 0.5em;
}

label {
    display: block;
    margin-bottom: 0.5em;
}

input[type="number"],
input[type="date"],
input[type="text"],
select {
    padding: 0.5em;
    border-radius: 4px;
    border: 1px solid #ccc;
    font-size: 1em;
    margin-bottom: 0.5em;
}

button[type="submit"] {
    background-color: #4CAF50;
    color: #fff;
    border: none;
    padding: 0.5em 1em;
    border-radius: 4px;
    font-size: 1em;
    cursor: pointer;
}

button[type="submit"]:hover {
    background-color: #3e8e41;
}

#report_results {
    margin-top: 2em;
    padding: 1em;
    background-color: #f5f5f5;
}
	</style>
</head>
<body>
	<h1 style = "color: green; text-align: center; ">Product Value Report</h1>
	<p style = "text-align: center;">Report generated from 01/01/2023 to 01/31/2023</p>
	<section>
		<h2>Filter Settings</h2>
		<form method="POST" action="{% url 'Transaction:filter' name %}">
			{% csrf_token %}
			<fieldset>
				<legend>Total Amount</legend>
				<label for="amount_lower">Lower Limit:</label>
				<input type="number" id="amount_lower" name="amount_lower" min="0" step="1">
				<label for="amount_upper">Upper Limit:</label>
				<input type="number" id="amount_upper" name="amount_upper" min="0" step="1">
			</fieldset>
			<fieldset>
				<legend>PIN Code</legend>
				<label for="pin_code">PIN Code:</label>
				<input type="number" id="pin_code" name="pin_code" maxlength="6">
			</fieldset>
			<fieldset>
				<legend>Customer</legend>
				<label for="customer_name">Customer Name:</label>
				<input type="text" id="customer_name" name="customer_name">
			</fieldset>
			<button type="submit">Apply Filters</button>
		</form>
	</section>
	<section>
		<!-- <p>{{ product_value }}</p> -->


        <div>
			<h2>Product Value Pie Chart</h2>
			<!-- <img src="customer_volume_pie_chart.png" alt="Customer Volume Pie Chart"> -->
			<canvas id="myChart" width="1300" height="600"></canvas>
	
		<script>
			var jsonStr = '{{ json_data|escapejs|safe }}';
			var data = JSON.parse(jsonStr);
		
			// Convert dictionary data to arrays for chart.js
			var labels = Object.keys(data);
			var values = Object.values(data);
		
			// Create a pie chart
			var ctx = document.getElementById('myChart').getContext('2d');
			var myChart = new Chart(ctx, {
				type: 'pie',
				data: {
					labels: labels,
					datasets: [{
						data: values,
						borderWidth: 1
					}]
				},
				options: {
					responsive: false,
					maintainAspectRatio: false
				}
			});
		</script>
		</div>

		<p>Descriptive Statistics:</p>
	<table>
		<tr>
			<th>Product Name</th>
			<th>Total Value</th>
		</tr>
		{% for key, value in product_value.items %}
		<tr>
			<td>{{ key }}</td>
			<td>{{ value }}</td>
			
		</tr>
		{% endfor %}
	</table>
    <p>click here to go <a href=" {% url 'Transaction:Home' %}">Home </a>page</p>
</body>
</html>